import { defineConfig } from 'vite';
import tailwindcss from '@tailwindcss/vite';
import { readFileSync } from 'fs';

// Inject live content counts into index.html meta tags at build/serve time, so
// the share-preview text never drifts. Reads content-stats.json (regenerated by
// scripts/gen-stats.mjs in build:seo); falls back to current values if missing.
function contentStatsHtml() {
  return {
    name: 'fe4-content-stats-html',
    transformIndexHtml(html) {
      let s = { problemsLabel: '1,126', chapters: 15 };
      try { s = { ...s, ...JSON.parse(readFileSync(new URL('./content-stats.json', import.meta.url), 'utf8')) }; } catch { /* keep fallback */ }
      return html
        .replaceAll('%FE4_PROBLEMS%', s.problemsLabel)
        .replaceAll('%FE4_CHAPTERS%', String(s.chapters));
    },
  };
}

export default defineConfig({
  plugins: [tailwindcss(), contentStatsHtml()],
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          'vendor-react': ['react', 'react-dom', 'react-router-dom'],
          'vendor-katex': ['katex'],
        },
      },
    },
  },
  server: {
    proxy: {
      '/api': 'http://localhost:4000',
      '/ws': {
        target: 'ws://localhost:4000',
        ws: true,
      },
    },
  },
});
