const express = require('express');
const fs = require('fs');
const path = require('path');
const router = express.Router();

// Generated by scripts/gen-content.mjs from the website's bundled study content.
// Loaded once at startup and served as JSON to the mobile app. Public + cacheable
// (the content isn't secret and rarely changes).
const content = require('../content.json');
const FIGURES_DIR = path.join(__dirname, '..', 'figures'); // <figureId>.png images

const CACHE = 'public, max-age=86400'; // 1 day

// Chapter -> subtopic -> lesson structure (names only) for the nav.
router.get('/chapters', (req, res) => {
  res.set('Cache-Control', CACHE);
  res.json(content.chapters);
});

// One lesson with its teaching blocks and practice problems.
router.get('/lessons/:chapterId/:lessonId', (req, res) => {
  const lesson = content.lessons[`${req.params.chapterId}/${req.params.lessonId}`];
  if (!lesson) {
    res.status(404).send({ msg: 'Lesson not found' });
    return;
  }
  res.set('Cache-Control', CACHE);
  res.json(lesson);
});

// One problem by id — used to resolve spaced-review queue items.
router.get('/problems/:id', (req, res) => {
  const problem = content.problemsById[req.params.id];
  if (!problem) {
    res.status(404).send({ msg: 'Problem not found' });
    return;
  }
  res.set('Cache-Control', CACHE);
  res.json(problem);
});

// A problem figure, pre-rendered to a PNG (problem.diagram.figureId). Rendered
// in a real browser so the arrowheads/markers survive (flutter_svg drops them).
router.get('/figures/:figureId', (req, res) => {
  const id = req.params.figureId;
  if (!/^[a-f0-9]{16}$/.test(id)) {
    res.status(400).send({ msg: 'Invalid figure id' });
    return;
  }
  const file = path.join(FIGURES_DIR, `${id}.png`);
  if (!fs.existsSync(file)) {
    res.status(404).send({ msg: 'Figure not found' });
    return;
  }
  res.set('Cache-Control', CACHE);
  res.type('image/png').sendFile(file);
});

module.exports = router;
