const express = require('express');
const { verifyAuth } = require('../middleware/auth.js');
const DB = require('../database.js');
const { buildChapterProgress } = require('../progressState.js');

const router = express.Router();

// Generated by scripts/gen-content.mjs and shipped with the service. Required
// once at boot rather than per request: it is 3MB and never changes at runtime.
// A missing file must not take the whole service down, so this degrades to an
// empty content set and the endpoint 404s instead of crashing on every call.
let content = { chapters: [], lessons: {}, problemIndex: {} };
try {
  content = require('../content.json');
} catch (e) {
  console.error('[progress] content.json missing — progress endpoint disabled:', e.message);
}

const chapterById = {};
for (const c of content.chapters || []) chapterById[c.id] = c;

// GET /api/progress/chapter/:chapterId
//
// Read-only. Everything it returns is derived from answers already recorded
// against problemHistory since the product launched, so existing users see
// their real history the moment this ships. Nothing is written here and no
// migration was needed. See docs/progress-markers.md.
router.get('/chapter/:chapterId', verifyAuth, async (req, res) => {
  const chapter = chapterById[req.params.chapterId];
  if (!chapter) return res.status(404).send({ msg: 'Unknown chapter' });

  try {
    // One query for the whole chapter. problemHistory rows carry topicId
    // (the chapter), so a single fetch covers every lesson plus practice.
    const historyRows = await DB.getProblemHistoryForChapter(req.user.email, chapter.id);
    return res.send(buildChapterProgress({
      chapter,
      lessonsByKey: content.lessons,
      problemIndex: content.problemIndex,
      historyRows,
    }));
  } catch (e) {
    console.error('[progress] chapter lookup failed:', e.message);
    return res.status(500).send({ msg: 'Could not load progress' });
  }
});

module.exports = router;
