const { Resend } = require('resend');
const { recordSend } = require('./sendBudget.js');

const resend = new Resend(process.env.RESEND_API_KEY);
const fromEmail = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';
const appUrl = process.env.APP_URL || 'https://fe4raccoons.com';
const fromHeader = `FE for Raccoons <${fromEmail}>`;
// Personal From for the plain-text founder emails (pitch + follow-up), so they
// read like a note from Jerson, not a brand. Replies still go to REPLY_TO.
const jersonFrom = `Jerson Garcia <${fromEmail}>`;
// Replies go to the FE for Raccoons alias on our Google Workspace (Oqupa LLC),
// which is a real inbox — fe4raccoons.com has no MX, so replies there bounce.
const replyToEmail = process.env.REPLY_TO_EMAIL || 'fe4raccoons@oqupa.com';

// Live content counts (generated by scripts/gen-stats.mjs and deployed with the
// service). Safe require so a missing file can never break the mailer.
let CONTENT = { problemsLabel: '1,126' };
try { CONTENT = { ...CONTENT, ...require('./contentStats') }; } catch { /* use fallback */ }

const usingTestSender = fromEmail === 'onboarding@resend.dev';
if (usingTestSender) {
  // Loud, once-at-startup warning. The Resend test sender ONLY delivers to the
  // Resend account owner's own address — every other recipient is rejected, so
  // real users never get verification / reset / student-code emails. Set
  // RESEND_FROM_EMAIL to an address on a domain verified at resend.com/domains.
  console.warn(
    '[email] WARNING: RESEND_FROM_EMAIL is unset — using onboarding@resend.dev. ' +
    'This only delivers to the Resend account owner. Verify a domain and set ' +
    'RESEND_FROM_EMAIL so real users receive email.',
  );
}

// Low-level send. Returns { ok, id?, error? } — never throws — so callers can
// decide how to react (analytics never breaks a flow, but the student-code
// flow needs to know whether the code actually went out).
async function sendEmail({ to, subject, html, text, headers, from }) {
  try {
    const payload = { from: from || fromHeader, to, subject, replyTo: replyToEmail };
    if (html) payload.html = html;   // omit for pure plain-text sends (better Primary placement)
    if (text) payload.text = text;
    if (headers) payload.headers = headers;
    const r = await resend.emails.send(payload);
    if (r.error) {
      console.error(`[email] send to ${to} rejected:`, r.error.message);
      return { ok: false, error: r.error.message };
    }
    // Log successes too (recipient + Resend id) — "delivered" in Resend only
    // means the receiving server accepted it, so this is the breadcrumb for
    // diagnosing "accepted but never arrived" (e.g. quarantined upstream).
    console.log(`[email] sent to ${to} — "${subject}" (id ${r.data?.id})`);
    await recordSend(); // count toward the Resend free-plan daily/monthly budget
    return { ok: true, id: r.data?.id };
  } catch (err) {
    console.error(`[email] send to ${to} threw:`, err.message);
    return { ok: false, error: err.message };
  }
}

/* ── Branded templates ──────────────────────────────────────────────────────
   Email clients are hostile: no <style>/flexbox reliability, images blocked by
   default, custom fonts mostly unsupported. So the layout is table-based with
   inline styles, the brand wordmark is rendered as TEXT (always visible, no
   blocked image), and fonts degrade gracefully to Arial. Colors/voice follow
   the FE for Raccoons brand. */
const C = {
  ember: '#E8683A', charcoal: '#2C2C2C', cream: '#FFF9F0', card: '#FFFFFF',
  body: '#5C584F', mute: '#A09C93', line: '#F0E9DB', emberBg: '#FEF0EA', emberLine: '#F6C9B6',
};
const SANS = "'DM Sans','Helvetica Neue',Arial,sans-serif";
const BODYF = "'Inter','Helvetica Neue',Arial,sans-serif";
const MONO = "'JetBrains Mono','SFMono-Regular',Consolas,'Courier New',monospace";

function emailLayout({ preheader = '', heading, inner, unsubUrl = '' }) {
  const unsub = unsubUrl
    ? `<br><a href="${unsubUrl}" style="color:${C.mute};text-decoration:underline;">Unsubscribe from these emails</a>`
    : '';
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light only">
<title>${heading}</title>
</head>
<body style="margin:0;padding:0;background:${C.cream};-webkit-font-smoothing:antialiased;">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:${C.cream};font-size:1px;line-height:1px;">${preheader}</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${C.cream};">
    <tr><td align="center" style="padding:40px 16px;">
      <table role="presentation" width="520" cellpadding="0" cellspacing="0" style="width:520px;max-width:100%;">
        <tr><td align="center" style="padding-bottom:22px;">
          <span style="font-family:${SANS};font-weight:700;font-size:30px;letter-spacing:-1px;color:${C.charcoal};">FE<span style="color:${C.ember};">4</span></span>
          <span style="font-family:${SANS};font-weight:700;font-size:12px;letter-spacing:5px;color:${C.charcoal};margin-left:9px;">RACCOONS</span>
        </td></tr>
        <tr><td style="background:${C.card};border-radius:16px;border-top:4px solid ${C.ember};box-shadow:0 1px 3px rgba(44,44,44,0.04),0 6px 22px rgba(44,44,44,0.07);padding:40px 40px 36px;">
          <h1 style="margin:0 0 16px;font-family:${SANS};font-weight:700;font-size:23px;line-height:1.25;letter-spacing:-0.02em;color:${C.charcoal};">${heading}</h1>
          ${inner}
        </td></tr>
        <tr><td align="center" style="padding:22px 24px 0;">
          <p style="margin:0;font-family:${BODYF};font-size:12px;line-height:1.6;color:${C.mute};">
            FE for Raccoons &middot; free FE Civil exam prep<br>
            <a href="${appUrl}" style="color:${C.mute};text-decoration:underline;">fe4raccoons.com</a>${unsub}<br>
            <span style="color:${C.mute};">FE for Raccoons is a registered DBA of Oqupa LLC.</span>
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`;
}

// Plain personal-letter layout (no logo card, text-forward) for founder notes
// that should read 1:1 rather than as a campaign. Same footer disclosures.
function letterLayout({ preheader = '', inner, unsubUrl = '' }) {
  const unsub = unsubUrl
    ? ` &middot; <a href="${unsubUrl}" style="color:${C.mute};text-decoration:underline;">Unsubscribe</a>`
    : '';
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light only">
<title>FE for Raccoons</title>
</head>
<body style="margin:0;padding:0;background:#ffffff;-webkit-font-smoothing:antialiased;">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:#ffffff;font-size:1px;line-height:1px;">${preheader}</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#ffffff;">
    <tr><td align="center" style="padding:36px 18px 44px;">
      <table role="presentation" width="544" cellpadding="0" cellspacing="0" style="width:544px;max-width:100%;">
        <tr><td style="font-family:${BODYF};font-size:16px;line-height:1.65;color:${C.charcoal};">
          ${inner}
        </td></tr>
        <tr><td style="padding:30px 0 0;">
          <p style="margin:0;padding-top:18px;border-top:1px solid ${C.line};font-family:${BODYF};font-size:12px;line-height:1.6;color:${C.mute};">
            FE for Raccoons &middot; free FE Civil exam prep &middot; <a href="${appUrl}" style="color:${C.mute};text-decoration:underline;">fe4raccoons.com</a>${unsub}<br>
            FE for Raccoons is a registered DBA of Oqupa LLC.
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`;
}

function para(html, extra = '') {
  return `<p style="margin:0 0 18px;font-family:${BODYF};font-size:15px;line-height:1.6;color:${C.body};${extra}">${html}</p>`;
}

function button(text, url) {
  return `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:4px 0 22px;"><tr>
    <td align="center" bgcolor="${C.ember}" style="border-radius:10px;">
      <a href="${url}" target="_blank" style="display:inline-block;padding:13px 36px;font-family:${SANS};font-weight:600;font-size:15px;line-height:1;color:#ffffff;text-decoration:none;border-radius:10px;">${text}</a>
    </td></tr></table>`;
}

// Founder sign-off: an optional closing line + Jerson's handwritten signature
// (a hosted image, with alt-text fallback if images are blocked) so lifecycle
// emails read like they come from a person.
function signatureBlock(closing = '') {
  const close = closing
    ? `<p style="margin:0 0 10px;font-family:${BODYF};font-size:15px;line-height:1.6;color:${C.body};">${closing}</p>`
    : '';
  return `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:28px 0 0;"><tr>
    <td style="padding-top:20px;border-top:1px solid ${C.line};">
      ${close}
      <img src="${appUrl}/sig-jerson.png" alt="Jerson Garcia" width="188" style="display:block;width:188px;max-width:62%;height:auto;margin:2px 0 4px;">
      <p style="margin:0;font-family:${BODYF};font-size:13px;line-height:1.5;color:${C.mute};">Founder, FE for Raccoons</p>
    </td></tr></table>`;
}

function fallbackLink(url) {
  return `<p style="margin:0 0 4px;font-family:${BODYF};font-size:12px;line-height:1.5;color:${C.mute};">Or paste this link into your browser:</p>
  <p style="margin:0;font-family:${MONO};font-size:12px;line-height:1.5;word-break:break-all;color:${C.ember};">${url}</p>`;
}

function noteLine(html) {
  return `<p style="margin:22px 0 0;padding-top:18px;border-top:1px solid ${C.line};font-family:${BODYF};font-size:13px;line-height:1.5;color:${C.mute};">${html}</p>`;
}

function ctaEmail({ heading, body, ctaText, ctaUrl, note }) {
  return emailLayout({
    preheader: body.replace(/<[^>]+>/g, '').slice(0, 100),
    heading,
    inner: `${para(body)}${button(ctaText, ctaUrl)}${fallbackLink(ctaUrl)}${noteLine(note || "If you didn't request this, you can safely ignore this email.")}`,
  });
}

function codeEmail({ heading, body, code }) {
  const block = `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:6px 0 18px;"><tr>
    <td align="center" style="background:${C.emberBg};border:1px solid ${C.emberLine};border-radius:12px;padding:20px 0;">
      <span style="font-family:${MONO};font-size:34px;font-weight:700;letter-spacing:12px;color:${C.ember};padding-left:12px;">${code}</span>
    </td></tr></table>`;
  return emailLayout({
    preheader: `Your verification code is ${code}`,
    heading,
    inner: `${para(body)}${block}${noteLine("This code expires in 15 minutes. If you didn't request it, you can ignore this email.")}`,
  });
}

async function sendPasswordResetEmail(toEmail, rawToken) {
  return sendEmail({
    to: toEmail,
    subject: 'Reset your FE for Raccoons password',
    html: ctaEmail({
      heading: 'Reset your password',
      body: 'We got a request to reset your password. Tap the button below to choose a new one — this link expires in 1 hour.',
      ctaText: 'Reset password',
      ctaUrl: `${appUrl}/reset-password/${rawToken}`,
    }),
  });
}

async function sendVerificationEmail(toEmail, rawToken) {
  return sendEmail({
    to: toEmail,
    subject: 'Verify your email — FE for Raccoons',
    html: ctaEmail({
      heading: 'Verify your email',
      body: "Welcome to FE for Raccoons! Confirm your email to secure your account and keep your progress, XP, and days studied synced everywhere.",
      ctaText: 'Verify email',
      ctaUrl: `${appUrl}/verify-email/${rawToken}`,
    }),
  });
}

// Student-discount verification: a 6-digit code to prove the student controls
// an academic inbox before the discounted price is unlocked.
async function sendStudentCodeEmail(toEmail, code) {
  return sendEmail({
    to: toEmail,
    // Subject must NOT lead with the numeric code — university mail filters
    // (e.g. Microsoft Defender) quarantine code-first subjects. Code lives in
    // the body; see docs/EMAIL-SETUP.md "University inboxes".
    subject: 'Your FE for Raccoons student code',
    html: codeEmail({
      heading: 'Verify your student email',
      body: 'Enter this code on FE for Raccoons to unlock the student price on the Exam Simulation:',
      code,
    }),
  });
}

// Admin diagnostic: send a test email and report the raw result.
async function sendTestEmail(toEmail) {
  return sendEmail({
    to: toEmail,
    subject: 'FE for Raccoons — email delivery test',
    html: ctaEmail({
      heading: 'Email is working',
      body: 'If you can read this, transactional email delivery is configured correctly and on-brand.',
      ctaText: 'Open FE for Raccoons',
      ctaUrl: appUrl,
      note: 'This is a test email sent from the admin panel.',
    }),
  });
}

/* ── Lifecycle emails (welcome / weekly digest / win-back) ───────────────────
   These are engagement emails, not transactional, so they carry an unsubscribe
   link + List-Unsubscribe headers for one-click opt-out and sender reputation. */
function lifecycleHeaders(unsubUrl) {
  return {
    'List-Unsubscribe': `<${unsubUrl}>`,
    'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
  };
}

function bullets(items) {
  const rows = items.filter(Boolean).map((i) =>
    `<tr><td style="padding:3px 0;font-family:${BODYF};font-size:15px;line-height:1.5;color:${C.body};"><span style="color:${C.ember};font-weight:700;">&bull;</span>&nbsp;&nbsp;${i}</td></tr>`).join('');
  return `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 0 22px;">${rows}</table>`;
}

// The exam-simulation footer for the weekly digest.
//
// Deliberately styled DOWN: a hairline rule, a muted overline and no button, so
// it reads as a footnote under the user's own numbers rather than as the point
// of the email. The digest is a report on their week; the moment it looks like
// an ad wearing a report's clothes, the report stops being trusted.
//
// The price is stated rather than hidden behind the click. Somebody who arrives
// at a price they did not expect feels baited, and that costs more than the
// clicks a coy version would earn.
//
// Link goes through /go/digest so this surface is counted separately from the
// banner, the card and the nav (ADR-0007).
function simDigestFooter() {
  return `<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="margin:26px 0 0;">
    <tr><td style="border-top:1px solid ${C.line};padding-top:20px;">
      <p style="margin:0 0 6px;font-family:${SANS};font-weight:600;font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:${C.mute};">Before exam day</p>
      <p style="margin:0 0 8px;font-family:${SANS};font-weight:600;font-size:16px;line-height:1.35;color:${C.charcoal};">Sit one full, timed exam</p>
      <p style="margin:0 0 10px;font-family:${BODYF};font-size:14px;line-height:1.6;color:${C.body};">110 questions over 5 hours 20 minutes, matched to the NCEES topic distribution, then a score report broken down by chapter so you can see where the points actually went. $49, or $29 with a verified .edu email. One time, and it does not expire.</p>
      <p style="margin:0 0 12px;font-family:${BODYF};font-size:14px;line-height:1.6;color:${C.body};">Everything else on FE for Raccoons stays free.</p>
      <a href="${appUrl}/go/digest" target="_blank" style="font-family:${SANS};font-weight:600;font-size:14px;color:${C.ember};text-decoration:none;">See what's in it &rarr;</a>
    </td></tr>
  </table>`;
}

// Humanize a chapter key for display ('water-resources' -> 'Water Resources').
function chapterLabel(key) {
  if (!key) return '';
  return /[-_]/.test(key)
    ? key.replace(/[-_]+/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
    : key;
}

// Sent the morning after a user verifies. Adaptive: if they already took the
// diagnostic, point them at their next study session instead of nagging them to
// do something they've done; otherwise, get them to the diagnostic.
async function sendWelcomeEmail(toEmail, { unsubUrl, diagnosticDone = false, focusChapter = null } = {}) {
  if (diagnosticDone) {
    const focus = chapterLabel(focusChapter);
    return sendEmail({
      to: toEmail,
      subject: 'Your study plan is ready',
      headers: lifecycleHeaders(unsubUrl),
      html: emailLayout({
        preheader: 'Nice start — here\'s your best next move.',
        heading: 'Your plan is ready.',
        unsubUrl,
        inner:
          para('Great start — your diagnostic is done, so your study plan is built around your real weak spots.') +
          (focus
            ? para(`<strong>Best place to begin: ${focus}</strong> — it\'s your lowest area right now, so it\'s where focused practice moves your score the most.`)
            : para('Jump back in and start with your lowest-mastery chapter — that\'s where focused practice moves your score the most.')) +
          button('Start studying', `${appUrl}/dashboard`) +
          para(`<span style="font-size:13px;color:${C.mute};">Everything here is free, lessons, ${CONTENT.problemsLabel} problems, your plan. The only paid thing is the full timed exam sim, if you ever want it.</span>`) +
          signatureBlock('Welcome aboard,'),
      }),
    });
  }
  return sendEmail({
    to: toEmail,
    subject: 'Start with the 5-minute diagnostic',
    headers: lifecycleHeaders(unsubUrl),
    html: emailLayout({
      preheader: 'Find your weak spots before you study a thing.',
      heading: "Welcome — let's pass the FE.",
      unsubUrl,
      inner:
        para('The smartest first move is the <strong>free quick start</strong>. Answer 5 questions — about 5 minutes — and it begins building your study plan around your weak spots, so you study what actually moves your score.') +
        button('Start the quick start', `${appUrl}/quickstart`) +
        para(`<span style="font-size:13px;color:${C.mute};">Everything here is free, lessons, ${CONTENT.problemsLabel} problems, the diagnostic. The only paid thing is the full timed exam sim, if you ever want it.</span>`) +
        signatureBlock('Welcome aboard,'),
    }),
  });
}

// Post-purchase follow-up for the exam simulator. Deliberately NOT sent at
// checkout (they're about to dive in). Two timed variants:
//   'firstExam' — the morning after they finish their first full sim (ideal)
//   'nudge'     — ~48h after purchase if they haven't run one yet
async function sendSimFollowupEmail(toEmail, { variant, scorePct = null, focusChapter = null, unsubUrl } = {}) {
  const focus = chapterLabel(focusChapter);
  if (variant === 'nudge') {
    return sendEmail({
      to: toEmail,
      subject: 'Your FE exam simulator is ready',
      headers: lifecycleHeaders(unsubUrl),
      html: emailLayout({
        preheader: "Whenever you're ready — here's how to get the most from it.",
        heading: "Your simulator's ready when you are.",
        unsubUrl,
        inner:
          para('You unlocked the full timed exam simulation — the single best way to prepare is to sit one all the way through.') +
          bullets([
            'Treat it like the real thing: full length, timed, no notes.',
            'Afterward, review <strong>every</strong> question — the ones you got right too.',
            focus ? `Then drill your weakest area (<strong>${focus}</strong>) and run it again.` : 'Then drill your weakest topics and run it again.',
          ]) +
          button('Start your exam', `${appUrl}/exam`) +
          para(`<span style="font-size:13px;color:${C.mute};">No rush, your access doesn't expire.</span>`) +
          signatureBlock('Rooting for you,'),
      }),
    });
  }
  // 'firstExam'
  return sendEmail({
    to: toEmail,
    subject: 'How did your first practice exam go?',
    headers: lifecycleHeaders(unsubUrl),
    html: emailLayout({
      preheader: 'Turn that sim into a score jump.',
      heading: 'Nice work on your first sim.',
      unsubUrl,
      inner:
        para(scorePct != null
          ? `You finished a full timed exam and scored <strong>${scorePct}%</strong> — a real baseline to build on. That single rep is one of the best things you can do to prepare.`
          : 'You finished a full timed exam — one of the best things you can do to prepare.') +
        para("Here's how to turn it into a score jump:") +
        bullets([
          'Review <strong>every</strong> question — the ones you got right too (lucky guesses hide gaps).',
          focus ? `Focus your lowest area: <strong>${focus}</strong>.` : 'Focus your lowest topics — your dashboard shows where.',
          'Retake in a week and watch the number climb.',
        ]) +
        para('Most people improve fast once they study by weakness instead of cramming everything.') +
        button('Review your results', `${appUrl}/exam`) +
        signatureBlock('Rooting for you,') +
        para(`<span style="font-size:13px;color:${C.mute};">Reply anytime, a real person reads these.</span>`),
    }),
  });
}

// Sent the morning after signup if the account is still unverified — one nudge
// (with a fresh link) so a missed/spam'd first email doesn't lose the user.
async function sendVerifyReminderEmail(toEmail, rawToken) {
  return sendEmail({
    to: toEmail,
    subject: 'Finish setting up your FE for Raccoons account',
    html: ctaEmail({
      heading: 'One step left — verify your email',
      body: "You created an account but haven't verified your email yet. Confirm it to secure your account and keep your progress, XP, and days studied synced everywhere.",
      ctaText: 'Verify email',
      ctaUrl: `${appUrl}/verify-email/${rawToken}`,
      note: "If you didn't create this account, you can ignore this email.",
    }),
  });
}

// Weekly recap (Sunday morning). Active users get the upbeat version; inactive
// users get a gentle restart so they don't just see a wall of zeros.
async function sendWeeklyDigestEmail(toEmail, d = {}) {
  const { active, weeklyXp = 0, streak = 0, problems = 0, masteryTo = null, focusChapter = null, unsubUrl, simPitch = false } = d;
  let subject; let heading; let inner; let preheader;
  if (active) {
    subject = `Your week: ${weeklyXp} XP, ${streak} days studied`;
    preheader = `${problems} problems solved this week`;
    heading = 'Your week in review';
    inner =
      bullets([
        `<strong>${weeklyXp}</strong> XP earned`,
        `<strong>${problems}</strong> problem${problems === 1 ? '' : 's'} solved`,
        `<strong>${streak}</strong> day${streak === 1 ? '' : 's'} studied`,
        masteryTo != null ? `Overall mastery: <strong>${masteryTo}%</strong>` : null,
      ]) +
      (focusChapter ? para(`<strong>Focus next week:</strong> ${focusChapter} — your weakest area right now.`) : '') +
      button('Continue studying', `${appUrl}/dashboard`);
  } else {
    subject = 'Your FE goal is still here';
    preheader = 'A 5-minute restart';
    heading = 'Your FE goal is still here';
    inner =
      para(`No study time logged this week, and that's okay. Five minutes today restarts the momentum.${focusChapter ? ` Your weakest area right now is <strong>${focusChapter}</strong>.` : ''}`) +
      button('Study 5 questions', `${appUrl}/dashboard`);
  }
  inner += signatureBlock('Rooting for you,');
  // Below the sign-off on purpose: the digest ends as a personal note, and the
  // offer sits underneath it as a footnote. The caller decides who sees it
  // (shouldPitchSimInDigest) — never buyers, never the inactive branch.
  if (simPitch) inner += simDigestFooter();
  return sendEmail({ to: toEmail, subject, headers: lifecycleHeaders(unsubUrl), html: emailLayout({ preheader, heading, inner, unsubUrl }) });
}

// Exam-date countdown. Copy adapts to how close exam day is.
async function sendExamCountdownEmail(toEmail, { daysLeft, readiness = null, focusChapter = null, unsubUrl, simPitch = false, trackToken = null, firstName = null } = {}) {
  // A few weeks out and they don't own the sim yet: a short, personal letter from
  // Jerson (plain layout, no campaign styling) with the one piece of advice that
  // matters most, backed by Mitch's story. Links tracked via /api/track.
  if (simPitch && daysLeft > 1) {
    // Plain-text personal note (no HTML, no images, no price) for the best shot
    // at the Primary inbox. Clean /go links still count clicks.
    const greeting = firstName ? `Hey ${firstName}, it's Jerson.` : "Hey, it's Jerson.";
    const text = `${greeting}

I started FE for Raccoons, and with your exam about ${daysLeft} days out, here's the one piece of advice I'd give a friend taking the FE.

Before exam day, sit one full, timed exam, start to finish. All 110 questions, 5 hours 20 minutes, no stopping.

The material is rarely the problem. It's the pace, the fatigue, and the format. One full run ahead of time removes all of that, so exam day feels familiar instead of overwhelming, and it's the single biggest thing you can do to be ready.

Don't take my word for it. Mitch did exactly this and passed the FE Civil on his first try. He says it better than I can, 40 seconds:
${appUrl}/go/mitch

That's what the Exam Simulation is for: one full, timed run before the real one, and your access never expires.

If you have a free weekend before your exam, block one morning for it. You'll walk in already knowing how it feels.

Start here:
${appUrl}/go/exam

Rooting for you,
Jerson Garcia
Founder, FE for Raccoons

P.S. If something's holding you back, or you just want to talk through your prep, hit reply. It comes straight to me.

FE for Raccoons is a registered DBA of Oqupa LLC.
Unsubscribe: ${unsubUrl}`;
    const goMitch = `${appUrl}/go/mitch`;
    const goExam = `${appUrl}/go/exam`;
    const link = (url, t) => `<a href="${url}" style="color:${C.ember};font-weight:600;text-decoration:none;">${t}</a>`;
    const html = letterLayout({
      preheader: 'The single biggest thing you can do to be ready.',
      unsubUrl,
      inner:
        para(greeting) +
        para(`I started FE for Raccoons, and with your exam about ${daysLeft} days out, here's the one piece of advice I'd give a friend taking the FE.`) +
        para('Before exam day, <strong>sit one full, timed exam, start to finish.</strong> All 110 questions, 5 hours 20 minutes, no stopping.') +
        para("The material is rarely the problem. It's the pace, the fatigue, and the format. One full run ahead of time removes all of that, so exam day feels familiar instead of overwhelming, and it's the single biggest thing you can do to be ready.") +
        para(`Don't take my word for it. <strong>Mitch did exactly this and passed the FE Civil on his first try.</strong> He says it better than I can, 40 seconds: ${link(goMitch, 'watch his story')}`) +
        para("That's what the Exam Simulation is for: one full, timed run before the real one, and your access never expires.") +
        para("If you have a free weekend before your exam, block one morning for it. <strong>You'll walk in already knowing how it feels.</strong>") +
        para(link(goExam, 'Start your exam simulation'), 'font-weight:600;') +
        para(`Rooting for you,<br>Jerson Garcia<br><span style="color:${C.mute};">Founder, FE for Raccoons</span>`) +
        para("<strong>P.S.</strong> If something's holding you back, or you just want to talk through your prep, hit reply. It comes straight to me.", `font-size:14px;color:${C.mute};margin-top:14px;`),
    });
    return sendEmail({
      to: toEmail,
      from: jersonFrom,
      subject: firstName ? `Hey ${firstName}, it's Jerson` : "Hey, it's Jerson",
      html,
      text,
    });
  }

  let subject; let heading; let body; let ctaText;
  if (daysLeft <= 0) {
    subject = "It's exam day — you've got this";
    heading = "Today's the day";
    body = "Trust your prep. Read each question carefully, lean on the Handbook, and keep moving — don't get stuck on any one problem. You've put in the work. Go pass the FE.";
    ctaText = null;
  } else if (daysLeft === 1) {
    subject = 'Your FE exam is tomorrow';
    heading = 'One day to go';
    body = `Keep it light today, then rest.${focusChapter ? ` If you review one thing, make it <strong>${focusChapter}</strong>.` : ''} A good night's sleep beats late cramming — you're ready.`;
    ctaText = 'Review your weak areas';
  } else {
    subject = `Your FE exam is in ${daysLeft} days`;
    heading = `${daysLeft} days to exam day`;
    const rd = readiness != null ? `You're at <strong>${readiness}% readiness</strong>. ` : '';
    body = `${rd}${focusChapter
      ? `Your biggest score lever right now is <strong>${focusChapter}</strong> — point your next few sessions there.`
      : 'Point your next few sessions at your weakest chapters between now and exam day.'}`;
    ctaText = 'Keep studying';
  }
  return sendEmail({
    to: toEmail,
    subject,
    headers: lifecycleHeaders(unsubUrl),
    html: emailLayout({
      preheader: daysLeft <= 0 ? 'Go pass the FE.' : `${daysLeft} days to go`,
      heading,
      unsubUrl,
      inner: para(body) + (ctaText ? button(ctaText, `${appUrl}/dashboard`) : '') + signatureBlock('Rooting for you,'),
    }),
  });
}

// One-time nudge for people who CLICKED the exam-sim pitch but haven't bought
// (~48h later). Warmer + lower-pressure than the pitch itself: they already
// showed interest, so address the real hesitations (time + cost) and invite a
// reply. Both links are tracked (same as the pitch).
async function sendSimPitchFollowupEmail(toEmail, { unsubUrl, trackToken = null, firstName = null } = {}) {
  // Plain-text personal follow-up (no HTML/images/price) for Primary placement.
  const greeting = firstName ? `Hey ${firstName}, it's Jerson again.` : "Hey, it's Jerson again.";
  const text = `${greeting}

I'm not trying to sell you anything (that's why I made the whole site free). I just want you ready on exam day, not in a panic. And honestly, one full, timed run does half the work of getting you there.

The material is rarely what surprises people. It's the pace and the fatigue, and doing one timed exam now means none of that is new when it counts.

Mitch was weighing it too, then ran it and passed the FE Civil on his first try. He explains why in 40 seconds:
${appUrl}/go/mitch

It's the Exam Simulation: one full, timed run, and your access never expires. One free weekend is all it takes.

Start here:
${appUrl}/go/exam

Rooting for you,
Jerson Garcia
Founder, FE for Raccoons

P.S. If something's holding you back, hit reply and tell me, maybe I can help. And if the timing is just off, no worries at all.

FE for Raccoons is a registered DBA of Oqupa LLC.
Unsubscribe: ${unsubUrl}`;
  const goMitch = `${appUrl}/go/mitch`;
  const goExam = `${appUrl}/go/exam`;
  const link = (url, t) => `<a href="${url}" style="color:${C.ember};font-weight:600;text-decoration:none;">${t}</a>`;
  const html = letterLayout({
    preheader: 'A quick, honest nudge before your FE.',
    unsubUrl,
    inner:
      para(greeting) +
      para("I'm not trying to sell you anything (that's why I made the whole site free). I just want you ready on exam day, not in a panic. And honestly, <strong>one full, timed run does half the work of getting you there.</strong>") +
      para("The material is rarely what surprises people. It's the pace and the fatigue, and doing one timed exam now means none of that is new when it counts.") +
      para(`Mitch was weighing it too, then ran it and <strong>passed the FE Civil on his first try.</strong> He explains why in 40 seconds: ${link(goMitch, 'watch his story')}`) +
      para("It's the Exam Simulation: one full, timed run, and your access never expires. One free weekend is all it takes.") +
      para(link(goExam, 'Start your exam simulation'), 'font-weight:600;') +
      para(`Rooting for you,<br>Jerson Garcia<br><span style="color:${C.mute};">Founder, FE for Raccoons</span>`) +
      para("<strong>P.S.</strong> If something's holding you back, hit reply and tell me, maybe I can help. And if the timing is just off, no worries at all.", `font-size:14px;color:${C.mute};margin-top:14px;`),
  });
  return sendEmail({
    to: toEmail,
    from: jersonFrom,
    subject: firstName ? `Hey ${firstName}, it's Jerson again` : "Hey, it's Jerson again",
    html,
    text,
  });
}

// One-time nudge for users who've gone quiet (~7 days).
async function sendWinbackEmail(toEmail, { focusChapter = null, unsubUrl } = {}) {
  return sendEmail({
    to: toEmail,
    subject: 'Still aiming for the FE?',
    headers: lifecycleHeaders(unsubUrl),
    html: emailLayout({
      preheader: 'Your account is right where you left it.',
      heading: 'Still aiming for the FE?',
      unsubUrl,
      inner:
        para(`Your account's right where you left it. The fastest restart: 5 questions in your weakest chapter${focusChapter ? ` (<strong>${focusChapter}</strong>)` : ''}.`) +
        button('Resume studying', `${appUrl}/dashboard`) +
        signatureBlock("You've got this,"),
    }),
  });
}

// Internal owner alert — fires when someone buys the Exam Simulation. Goes to
// OWNER_ALERT_EMAIL (defaults to the owner's inbox). Not a lifecycle email, so
// no unsubscribe; it's a private notification.
async function sendSaleAlertEmail({ buyerEmail = null, amountCents = 0, tier = null, totalSales = null, totalRevenueCents = null } = {}) {
  const to = process.env.OWNER_ALERT_EMAIL || 'jersondevs@gmail.com';
  const money = (c) => `$${(Math.round(c) / 100).toFixed(2).replace(/\.00$/, '')}`;
  const tierLabel = tier === 'student' ? 'Student' : tier === 'standard' ? 'Standard' : (tier || '—');
  const rows = [
    `<strong>Amount:</strong> ${money(amountCents)}`,
    `<strong>Tier:</strong> ${tierLabel}`,
    `<strong>Buyer:</strong> ${buyerEmail || 'unknown'}`,
    totalSales != null
      ? `<strong>Total sales:</strong> ${totalSales}${totalRevenueCents != null ? ` (${money(totalRevenueCents)})` : ''}`
      : null,
  ];
  return sendEmail({
    to,
    subject: `New Exam Simulation sale — ${money(amountCents)}`,
    html: emailLayout({
      preheader: `${buyerEmail || 'Someone'} just bought the Exam Simulation.`,
      heading: 'You made a sale',
      inner: para('Someone just purchased the Exam Simulation on FE for Raccoons.') + bullets(rows) + para('Nice work.'),
    }),
  });
}

function getEmailConfig() {
  return { from: fromEmail, usingTestSender, appUrl };
}

module.exports = {
  sendSaleAlertEmail,
  sendPasswordResetEmail,
  sendVerificationEmail,
  sendVerifyReminderEmail,
  sendStudentCodeEmail,
  sendTestEmail,
  sendWelcomeEmail,
  sendWeeklyDigestEmail,
  sendWinbackEmail,
  sendExamCountdownEmail,
  sendSimFollowupEmail,
  sendSimPitchFollowupEmail,
  getEmailConfig,
};
