// Writes the live content counts to two build artifacts so non-React consumers
// (index.html meta via vite, prerendered SEO pages, og-image, and the Node
// email templates) all read the same numbers the app shows. Regenerated on
// every build:seo. Resilient — never breaks the build.
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { liveCounts } from './content-counts.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

try {
  const c = await liveCounts();
  const data = { problems: c.problems, lessons: c.lessons, chapters: c.chapters, problemsLabel: c.problemsLabel };
  // For the build (vite plugin, prerender, gen-og).
  writeFileSync(join(root, 'content-stats.json'), JSON.stringify(data, null, 2) + '\n');
  // CJS module the Node server can require (deployed with service/*.js).
  writeFileSync(
    join(root, 'service/contentStats.js'),
    `// AUTO-GENERATED by scripts/gen-stats.mjs — do not edit by hand.\nmodule.exports = ${JSON.stringify(data, null, 2)};\n`,
  );
  console.log(`[gen-stats] ${c.chapters} chapters · ${c.lessons} lessons · ${c.problemsLabel} problems`);
} catch (e) {
  console.warn('[gen-stats] skipped (kept existing stats): ' + e.message);
  process.exit(0);
}
